spring:
  datasource:
    username: ${username}
    password: ${password}
    url: jdbc:mysql://davideducation.cb8kekey60qs.ap-northeast-2.rds.amazonaws.com:3306/DavidEducationDATABASE?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
  jwt:
    secret: 'Epjma2vvW+NPGurRKItFl9f6QMokFo/HwEArhEQS+U4='
    access-token-time: 3600000

iamport:
  api_key: ${iamport_Rest_Api_Key}
  api_secret: ${iamport_Rest_Api_Secret}